config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: :index
  resources :states, only: :index
  default_url_options host: "https://carrier-door.herokuapp.com"

  root to: 'home#index'

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions',
    confirmations: 'companies/confirmations'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    get 'home/applied_job_list', on: :member
    resources :opening_jobs do
      get 'jobs_list', on: :collection
      get 'applied_jobs/new', to: 'applied_jobs#new',on: :member
      post '/applied_jobs', to: 'applied_jobs#create',on: :member, as: 'applied'
      delete '/applied_jobs', to: 'applied_jobs#destroy',on: :member, as: 'un_apply'
      get 'apply', on: :member
      get 'interested', on: :member
    end
  end

  
  resources :companies, only: %i[index show] do
    get 'chat', on: :member
    resources :charges, on: :member
    resources :company_reviews
    resources :opening_jobs do
      member do
        get 'interested_people'
        get 'open_close_post'
      end
    end
  end
  
  resources :technologies
  resources :super_admins do
    get 'charges/index', on: :collection
    member do
      get 'companies/approve_company'
      get 'companies/reject_company'
      get 'companies/unapprove_company'
    end
  end
  resources :resumes
  get '/applied_jobs/:job_id', to: 'applied_jobs#show', as:'applied_candidates'
  resources :messages do
    get 'new_message', on: :member
  end
end

app/controllers/super_admins_controller.rb
# frozen_string_literal: true

# super admins controller
class SuperAdminsController < ApplicationController
  before_action :authenticate_user!, :check_user

  def index
    @companies = Company.where(approved: false)
  end

  def check_user
    redirect_to root_path if current_user.has_role?(:user)
  end
end

app/views/super_admins/index.html.erb
<!-- MAIN CONTENT-->
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
        </div>
      </div>
      <div class="row">
      <div class="col-lg-6">
       
      </div>
        <div class="col-lg-6">
          <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
            <div class="au-card-title" style="background-image:url('images/bg-title-01.jpg');">
              <div class="bg-overlay bg-overlay--blue"></div>
              <h3>
                <i class="zmdi zmdi-account-calendar"></i>Companies Request(Live)</h3>
              <button class="au-btn-plus">
                <i class="zmdi zmdi-plus"></i>
              </button>
            </div>
            <div class="au-task js-list-load">
              <div class="au-task__title">
                <p>Please approve or reject</p>
              </div>
              <div class="au-task-list js-scrollbar3">
                <div class="table-responsive table--no-card m-b-40">
            <table class="table table-borderless table-striped table-earning">
              <tbody id="clist">
                <% if @companies.present? %>
                  <% @companies.each do |company| %>
                  <tr>
                    <td title="Company details"><%= link_to company.name, company_path(company), style: "color:black;" %>
                    </td>
                    <td title="Approve the company"><%= link_to 'Approve', companies_approve_company_super_admin_path(company) %></td>
                    <td title="Reject the company"><%= link_to 'Reject', companies_reject_company_super_admin_path(company) %></td>
                  </tr>
                  <% end %>
                <% else %>
                  <h5 class="h5-danger">&nbsp;No Requests!</h5>
                <% end %>
              </tbody>
            </table>
          </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="copyright">
            <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END MAIN CONTENT-->
<!-- END PAGE CONTAINER-->
</div>

</div>
</body>