config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: :index
  resources :states, only: :index
  default_url_options host: "https://carrier-door.herokuapp.com"

  root to: 'home#index'

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions',
    confirmations: 'companies/confirmations'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    get 'home/applied_job_list', on: :member
    resources :opening_jobs do
      get 'jobs_list', on: :collection
      get 'applied_jobs/new', to: 'applied_jobs#new',on: :member
      post '/applied_jobs', to: 'applied_jobs#create',on: :member, as: 'applied'
      delete '/applied_jobs', to: 'applied_jobs#destroy',on: :member, as: 'un_apply'
      get 'apply', on: :member
      get 'interested', on: :member
    end
  end

  
  resources :companies, only: %i[index show] do
    get 'chat', on: :member
    resources :charges, on: :member
    resources :company_reviews
    resources :opening_jobs do
      member do
        get 'interested_people'
        get 'open_close_post'
      end
    end
  end
  
  resources :technologies
  resources :super_admins do
    get 'charges/index', on: :collection
    member do
      get 'companies/approve_company'
      get 'companies/reject_company'
      get 'companies/unapprove_company'
    end
  end
  resources :resumes
  get '/applied_jobs/:job_id', to: 'applied_jobs#show', as:'applied_candidates'
  resources :messages do
    get 'new_message', on: :member
  end
end

app/models/opening_job.rb
# frozen_string_literal: true

class OpeningJob < ApplicationRecord
  validates :experience, presence: true, format: { multiline: true, with: /^[0-9](\.[0-9]+)?$/, message: 'only digits are allowed' }
  validates :job_role, presence: true, format: { multiline: true, with: /^[a-zA-Z]+$/, message: 'only alphabetic characters are allowed.' }
  validates :description, presence: true, length: { maximum: 100 }
  validates :cgpa, presence: true, format: { multiline: true, with: /^[0-9](\.[0-9]+)?$/, message: 'only digits are allowed' }

  belongs_to :company
  has_many :interested_people, dependent: :destroy
  has_many :applied_jobs, dependent: :destroy
  has_many :users, through: :applied_jobs
  
  serialize :technologies, Array
  scope :open_job, -> { where(open: true) }

  after_create :notify_user
  before_save do
    self.technology_id.gsub!(/[\[\]\"]/,"") if attribute_present?("technology_id")
  end
  def notify_user
    users = User.all
    users.each do |user|
      NotifyUsersMailer.notify_users_for_new_job(user, self).deliver
    end
  end

end

app/controllers/opening_jobs_controller.rb
# frozen_string_literal: true

class OpeningJobsController < ApplicationController
  before_action :find_job, only: %i[edit update destroy interested_people show
                                    open_close_post]
  before_action :find_company, only: %i[new create edit interested_people
                                        open_close_post]
  def index
    @jobs = current_company.opening_jobs
  end

  def new
    @job = OpeningJob.new
    @technologies = Technology.all
  end

  def create
    @job = OpeningJob.new(jobs_params)
    if @job.save!
      redirect_to company_opening_jobs_path, notice: 'Job #been added!'
    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def update
    if @job.update(jobs_params)
      redirect_to company_opening_jobs_path, notice: 'Job updated'
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy
    redirect_to company_opening_jobs_path
  end

  def interested_people
    @interested_people = @job.users
  end

  def jobs_list
    @jobs = OpeningJob.open_job
  end

  def apply
    if current_user.opening_jobs.where(id: params[:id]).blank?

      job = current_user.interested_people.find_by(opening_job_id: params[:id])
      binding.pry
      if job.applied?
        job.update(user_id: current_user.id,
                   opening_job_id: params[:id],
                   applied: false)
      else
        job.update(user_id: current_user.id,
                   opening_job_id: params[:id],
                   applied: true)
      end
      redirect_to jobs_list_user_opening_jobs_path, notice: 'Done!'
    else

      job = InterestedPerson.new(user_id: current_user.id,
                                 opening_job_id: params[:id],
                                 applied: true)
      if job.save!
        redirect_to jobs_list_user_opening_jobs_path, notice: 'Applied!'
      else
        flash[:alert] = 'Something went wrong'
        render 'new'
      end
    end
  end

  def interested
    if current_user.opening_jobs.where(id: params[:id]).blank?
      job = InterestedPerson.new(user_id: current_user.id,
                                 opening_job_id: params[:id])
      if job.save!
        redirect_to jobs_list_user_opening_jobs_path, notice: 'Interest recorded!'
      else
        flash[:alert] = 'Something went wrong'
        render 'new'
      end
    else
      redirect_to jobs_list_user_opening_jobs_path
    end
  end

  def open_close_post
    @job.update(open: !@job.open)
    redirect_to company_opening_jobs_path, notice: 'Done'
    # respond_to do |format|
    #   format.js
    # end
    # redirect_to company_opening_jobs_path, notice: "Done"
  end

  private

  def jobs_params
    params.required(:opening_job).permit(:job_role, :company_id,
                                         :experience, :job_role,
                                         :description, :cgpa, technologies: [])
  end

  def find_job
    @job = OpeningJob.find(params[:id])
    @technologies = Technology.all
  end

  def find_company
    @company = Company.find(params[:company_id])
  end
end

app/helpers/opening_jobs_helper.rb
module OpeningJobsHelper
  
  def eligible?(job,current_user)
    current_user.years_of_experience >= job.experience
  end
  
  def interested?(job)
    current_user.opening_jobs.where(id: job.id).blank?
  end
  
  def applied?(job)
    if !interested?(job)
      jobb = current_user.interested_people.find_by(opening_job_id: job.id)
      jobb.nil? ? false : jobb.applied?
    end
  end

  def opened(job)
    job.open ? "Close" : "Open"
  end
end

app/views/opening_jobs/_form.html.erb
<div class="popular_catagory_area" style="padding-top: 5px;">
  <div class="container">
    <div class="row h-100 justify-content-center align-items-top">
      <div class="col-10 col-md-8 col-lg-6">
        <%= form_with(model: [@company, @job], validate: true, local: true) do |f| %>
          <% if @job.errors.any? %>
            <h2><%= pluralize(@job.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% @job.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>

          <div class="form-group">
            <%= f.label :job_role %><span class="myspan">*</span><br />
            <%= f.text_field :job_role, autofocus: true, autocomplete: "job_role", class: "au-input au-input--full" %>
          </div>

          <div class="form-group"><span class="myspan">&nbsp;</span>
            <%= f.label :description %><br />
            <%= f.text_area :description, autofocus: true, autocomplete: "description", class: "au-input au-input--full" %>
          </div>

          <div class="form-group"><span class="myspan">*</span>
            <%= f.label :minimum_experience %><br />
            <%= f.number_field :experience, autofocus: true, min: 0, value: 1, class: "au-input au-input--full" %>
          </div>

          <div class="form-group"><span class="myspan">*</span>
            <%= f.label :minimum_cgpa %><br />
            <%= f.text_field :cgpa, autofocus: true, min: 0, value: 8.00, class: "au-input au-input--full" %>
          </div>

          <div class="form-group"><span class="myspan">*</span>
            <%= f.label :technology %><br />
            <% @technologies.each do |technology|%>
            <%= f.check_box :technologies, {multiple: true}, technology.technology_name, false %>
            <%= f.label technology.technology_name%>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.hidden_field :company_id, value: @company.id %>
          </div>

          <br />
          <div class="field">
            <%= f.submit "create job",class: "btn btn-primary btn-lg" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/opening_jobs/_index_jobs.html.erb
<% if @jobs.present? %>
  <% @jobs.each do |job| %>
    <tr>
      <td title ="Job Role"><%= job.job_role %></td>
      <td title ="Technology"><%= job.technology.technology_name %></td>
      <td title ="Experience"><%= job.experience %></td>
      <td title ="CGPA"><%= job.cgpa %></td>
      <td><%= link_to "",  edit_company_opening_job_path(current_company,job), class: "btn btn-outline-primary btn-sm fa fa-pencil-square-o", title: "Edit post" %></td>
      <td><%= link_to "", company_opening_job_path(current_company,job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm fa fa-trash", title: "Delete Job post" %></td>
      <td><%= link_to "Interested",  interested_people_company_opening_job_path(current_company,job), class: "btn btn-outline-success fa fa-users btn-sm", title: "Interested People" %></td>
      <td><%= link_to opened(job),  open_close_post_company_opening_job_path(current_company,job), class: "btn btn-outline-primary fa btn-sm", title: "Open/Close", remote: true, id: "open_close" %></td>
    </tr>
  <% end %>
<% else %>
  <span style="color: red; font-weight: bold">***Data not available</span>
<% end %>

app/views/opening_jobs/_interested.html.erb
<% # <% binding.pry %>
<% if @interested_people.present? %>
  <% @interested_people.each do |person| %>
    <tr>
      <td title ="Username"><%= person.username %></td>
      <td title ="First Name"><%= person.firstname %></td>
      <td title ="Last Name"><%= person.lastname %></td>
      <td title ="Contact number"><%= person.contact %></td>
      <td title ="Email Address"><%= person.email %></td>
      <td title ="Experience in years"><%= person.years_of_experience %></td>
    </tr>
  <% end %>
<% else %>
  <span style="color: red; font-weight: bold">***Data not available</span>
<% end %>

app/views/opening_jobs/_jobs.html.erb
<% # <% binding.pry %>
<% if !@jobs.blank? %>
  <% @jobs.each do |job| %>
    <tr>
      <td title ="Job Role"><%= job.job_role %></td>
      <td title ="Technology"><%= job.technology.technology_name %></td>
      <td title ="Experience"><%= job.experience %></td>
      <td title ="CGPA"><%= job.cgpa %></td>
      <td><%= link_to "Edit",  edit_company_opening_job_path(current_company,job), class: "genric-btn info-border radius medium fa fa-pencil-square-o", title: "Edit post" %></td>
      <td><%= link_to "Delete", company_opening_job_path(current_company,job), method: :delete, data: { confirm: "Are you sure?" }, class: "genric-btn danger-border radius medium fa fa-trash", title: "Delete Job post" %></td>
    </tr>
  <% end %>
<% else %>
  <span style="color: red; font-weight: bold">***Data not available</span>
<% end %>

app/views/opening_jobs/_list_jobs.html.erb
<% if @jobs.present? %>
  <% @jobs.each do |job| %>
    <tr>
      <td title ="Comapany details"><%= image_tag job.company.avatar.url, class: "circleBase type2" %>
      &nbsp;<%= link_to job.company.name, company_path(job.company) %></td>
      <td title ="Job Role"><%= job.job_role %></td>
      <td title ="Technology"><%= job.technologies %></td>
      <td title ="Experience"><%= job.experience %></td>
      <td title ="CGPA"><%= job.cgpa %></td>
      <td><%= link_to "Open", user_opening_job_path(current_user, job), class: "btn btn-outline-success btn-sm" %></td>
      <td><%= "yes" if applied?(job) %></td>
    </tr>
  <% end %>
<% else %>
  <span style="color: red; font-weight: bold">***Data not available</span>
<% end %>

app/views/opening_jobs/edit.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/opening_jobs/index.html.erb
<% # <%= link_to "Back", admin_index_path %>
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="col-lg-12">
        <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
          <div class="au-card-inner">
            <div class="table-responsive">
              <%= link_to "Post a Job", new_company_opening_job_path , title: "Add new job", class: "btn btn-success fa fa-plus-circle" %></h6>
              <table class="table table-hover">
                <thead class="thead-light">
                  <tr>
                    <th>Job Role</th>
                    <th>Technology</th>
                    <th>Experience</th>
                    <th>CGPA</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id="index_jobs_list_body">
                  <%= render "index_jobs.html.erb" %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/opening_jobs/interested_people.html.erb
<% # <%= link_to "Back", admin_index_path %>
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="col-lg-12">
        <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
          <div class="au-card-inner">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead clas="thead-dark">
                  <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Contact No.</th>
                    <th>Email</th>
                    <th>Experience(y)</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id="interested_list_body">
                  <%= render "interested.html.erb" %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/opening_jobs/jobs_list.html.erb
<% # <%= link_to "Back", admin_index_path %>
<body class="animsition">
  <div class="page-wrapper">
    <div class="main-content">
      <div class="section__content section__content--p30">
        <div class="container-fluid">
          <div class="col-lg-12">
          <h3>Available Jobs</h3><br>
            <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
              <div class="au-card-inner">
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead class="thead-light">
                      <tr>
                        <th>Company</th>
                        <th>Job Role</th>
                        <th>Technology</th>
                        <th>Experience</th>
                        <th>CGPA</th>
                        <th></th>
                        <th>Applied?</th>
                      </tr>
                    </thead>
                    <tbody id="jobs_list_body">
                      <%= render "list_jobs.html.erb" %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/opening_jobs/new.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/opening_jobs/open_close_post.js.erb
if($('#open_close').text()=="Close"){
  $('#open_close').text('Open')
  alert("Closed!");
}else{
  $('#open_close').text('Close')
  alert("Opened!");
}

app/views/opening_jobs/show.html.erb
<body class="animsition">
  <%= link_to "Back ", jobs_list_user_opening_jobs_path %>||
  <%= link_to "Dashboard ", root_path %>||
  <div class="page-wrapper">
    <div class="main-content">
      <div class="section__content section__content--p30">
        <div class="container-fluid">
          <div class="col-lg-12">
            <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
              <div class="au-card-inner">
                <div class="table-responsive">
                  <h4>Company:</h4> <%= @job.company.name %><br />=========================<br />
                  <h4>Job Role:</h4> <%= @job.job_role %><br />=========================<br />
                  <h4>Technology:</h4> <%= @job.technology.technology_name %><br />=========================<br />
                  <h4>Job description:</h4> <%= @job.description %><br />=========================<br />
                  <h4>Job Experience(years):</h4> <%= @job.experience %><br />=========================<br />
                  <h4>CGPA:</h4> <%= @job.cgpa %><br /><br />
                  <% if interested?(@job) %>
                    <%= link_to 'Interested', interested_user_opening_job_path, class: "btn btn-warning" %>
                  <% end %>
                  <% if !applied?(@job) %>
                    <%= link_to 'Apply', apply_user_opening_job_path, data: { confirm: 'Are you sure?' }, class: "btn btn-success btn-sn" %>
                  <% else %>
                    <%= link_to 'Un-apply', apply_user_opening_job_path, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>