config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: :index
  resources :states, only: :index
  default_url_options host: "https://carrier-door.herokuapp.com"

  root to: 'home#index'

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions',
    confirmations: 'companies/confirmations'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    get 'home/applied_job_list', on: :member
    resources :opening_jobs do
      get 'jobs_list', on: :collection
      get 'applied_jobs/new', to: 'applied_jobs#new',on: :member
      post '/applied_jobs', to: 'applied_jobs#create',on: :member, as: 'applied'
      delete '/applied_jobs', to: 'applied_jobs#destroy',on: :member, as: 'un_apply'
      get 'apply', on: :member
      get 'interested', on: :member
    end
  end

  
  resources :companies, only: %i[index show] do
    get 'chat', on: :member
    resources :charges, on: :member
    resources :company_reviews
    resources :opening_jobs do
      member do
        get 'interested_people'
        get 'open_close_post'
      end
    end
  end
  
  resources :technologies
  resources :super_admins do
    get 'charges/index', on: :collection
    member do
      get 'companies/approve_company'
      get 'companies/reject_company'
      get 'companies/unapprove_company'
    end
  end
  resources :resumes
  get '/applied_jobs/:job_id', to: 'applied_jobs#show', as:'applied_candidates'
  resources :messages do
    get 'new_message', on: :member
  end
end

app/models/technology.rb
# frozen_string_literal: true

# technology model
class Technology < ApplicationRecord
  validates :technology_name, presence: true, format: { with: /[a-zA-Z]/, message: 'only alphabetic characters are allowed.'}
end

app/controllers/technologies_controller.rb
# frozen_string_literal: true

# crud operations for technology model
class TechnologiesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_technology, only: %i[edit update show destroy]

  def index
    @all_technologies = Technology.all
  end

  def new
    @new_technology = Technology.new
  end

  def create
    @new_technology = Technology.new(allowed_parameter)
    if @new_technology.save
      redirect_to technologies_path, notice: 'technology saved'
    else
      render :new, alert: 'technology not saved'
    end
  end

  def update
    if @added_technology.update(allowed_parameter)
      redirect_to technologies_path, notice: 'technology updated'
    else
      render :edit, alert: 'technology not updated'
    end
  end

  def destroy
    flash.alert = if @added_technology.destroy
                    'technology deleted successfully'
                  else
                    'technology is not deleted'
    end
    redirect_to technologies_path
  end

  private

  def allowed_parameter
    params.require(:technology).permit(:technology_name)
  end

  def find_technology
    @added_technology = Technology.find(params[:id])
  end
end

app/views/technologies/_new.html.erb
<div id="my_form">
  <a href="#" id="close_form" class="fa fa-times fa-3" ></a>
  <%= form_with model: @new_technology, url: technologies_path, validate: true do |f| %>
    <div class="form-group">
      <%= f.text_field :technology_name, class: "au-input au-input--full col-md-6", placeholder: "Enter technology" %>
      <%= f.submit "Add", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

app/views/technologies/_technologies_list.html.erb
<% @all_technologies.each do |technology| %>
  <tr>
    <td><%= technology.technology_name %></td>
    <td title="Edit"><%= link_to "Edit", edit_technology_path(technology.id), class: "btn btn-outline-primary fa fa-pencil-square-o" %></td>
    <td title="Show"><%= link_to "Show", technology_path(technology.id), class: "btn btn-outline-success fa fa-info-circle" %></td>
    <td title="Remove">
      <%= link_to "Remove", technology_path(technology.id), data: { confirm: 'are you sure?' }, method: :delete , remote: true, class: "btn btn-outline-danger fa fa-times-circle" %>
    </td>
  </tr>
<% end %>

app/views/technologies/edit.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <%= form_with model: @added_technology,  validate: true, local: true do |f| %>

            <div class="form-group">
              <%= f.label :technology_name %><br />
              <%= f.text_field :technology_name, class: "au-input au-input--full"  %>
            </div>

            <div class="form-group">
              <%= f.submit "submit", class: "btn btn-primary btn-lg" %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/technologies/index.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="col-lg-12">
        <div id="render_form"></div>
        <div id="new_tech_link">
          <%= link_to "Add new technology", new_technology_path, remote: true, class: "btn btn-success fa fa-plus-circle" %>
        </div>
        <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
          <div class="au-card-inner">
            <div class="table-responsive">
              <table class='table'>
                <thead>
                  <tr>
                    <th>Technology Name</th>
                  </tr>
                </thead>
                <tbody id="technology_tbody" >
                  <%= render "technologies_list" %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/technologies/new.js.erb
$('#render_form').html("<%= j render 'new' %>");
$('#new_tech_link').hide();

app/views/technologies/show.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="col-lg-12">
        <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
          <div class="au-card-inner">
            <div class="table-responsive">
              <table class='table'>

                <thead>
                  <tr>
                    <th>Technology Name</th>
                  </tr>
                </thead>

                <tbody>
                  <tr>
                    <td><%= @added_technology.technology_name %></td>
                    <td><%= link_to "edit", edit_technology_path(params[:id]), class: "btn btn-outline-primary fa fa-pencil-square-o" %></td>
                    <td>
                      <%= link_to "delete", technology_path(params[:id]), confirm: :'are you sure?', data: { method: :delete }, class: "btn btn-outline-danger fa fa-times-circle" %>
                    </td>
                  </tr>
                </tbody>

              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>