config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: :index
  resources :states, only: :index
  default_url_options host: "https://carrier-door.herokuapp.com"

  root to: 'home#index'

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions',
    confirmations: 'companies/confirmations'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    get 'home/applied_job_list', on: :member
    resources :opening_jobs do
      get 'jobs_list', on: :collection
      get 'applied_jobs/new', to: 'applied_jobs#new',on: :member
      post '/applied_jobs', to: 'applied_jobs#create',on: :member, as: 'applied'
      delete '/applied_jobs', to: 'applied_jobs#destroy',on: :member, as: 'un_apply'
      get 'apply', on: :member
      get 'interested', on: :member
    end
  end

  
  resources :companies, only: %i[index show] do
    get 'chat', on: :member
    resources :charges, on: :member
    resources :company_reviews
    resources :opening_jobs do
      member do
        get 'interested_people'
        get 'open_close_post'
      end
    end
  end
  
  resources :technologies
  resources :super_admins do
    get 'charges/index', on: :collection
    member do
      get 'companies/approve_company'
      get 'companies/reject_company'
      get 'companies/unapprove_company'
    end
  end
  resources :resumes
  get '/applied_jobs/:job_id', to: 'applied_jobs#show', as:'applied_candidates'
  resources :messages do
    get 'new_message', on: :member
  end
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

class ChargesController < ApplicationController
  def index
    @subscriptions = Subscription.all
  end

  def create
    @amount = 1500
    customer = Stripe::Customer.create({
                                         email: params[:stripeEmail],
                                         source: params[:stripeToken]
                                       })
    charge = Stripe::Charge.create({
                                     customer: customer.id,
                                     amount: @amount,
                                     description: 'Rails Stripe customer',
                                     currency: 'inr'
                                   })
    current_company.subscription.update(subscribed: true, subscription_date: DateTime.now)
  rescue Stripe::CardError => e
    redirect_to new_company_charge_path(params(:id)), error: e.message
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def days_left(subscription)
    diff = Time.now.utc - subscription.created_at
    days = ((15.days.seconds - diff) / 1.day).to_i
    (days < 0) ? 0 : days
  end
  
  def subscribed(subscription)
    subscription.subscribed ? "Yes" : "No"
  end
end

app/views/charges/_companies_list.html.erb
<% if @subscriptions.present? %>
  <% @subscriptions.each do |subscription| %>
    <% if subscription.company.approved? %>
    <tr>
      <td title="Company details">
        <%= image_tag subscription.company.avatar.url, 
        class: "circleBase "+ (subscription.company.approved ? "type2g": "type2r") %>
        &nbsp;<%= link_to subscription.company.name, company_path(subscription.company), style: "color:black;" %>
      </td>
      <td title ="Subscribed? "><%= subscribed(subscription) %></td>
      <td title="Days to complete trial"><%= days_left(subscription) %></td>
      <td title ="Subscription date"><%= subscription&.subscription_date %></td>
      <td title ="Un Approve"><%= link_to 'Un Approve', companies_approve_company_super_admin_path(subscription.company), class: "message btn btn-outline-danger btn-sm fa fa-thumbs-down", remote: true %></td>
    </tr>
    <% end %>
  <% end %>
<% else %>
  <span class="alert">***Data not available</span>
<% end %>

app/views/charges/create.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <h2>Thanks, you paid <strong>$5.00</strong>!</h2>
        <br />
        <%= link_to 'Dashboard', companies_path%>
      </div>
    </div>
  </div>
</div>

app/views/charges/index.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="col-lg-12">
        <h2 class="title-1 m-b-25">Companies list</h2>
        <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
          <div class="au-card-inner">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="thead-light">
                  <tr>
                    <th>Company Name</th>
                    <th>Subscription Taken?</th>
                    <th>Trial days</th>
                    <th>Subscription Date</th>
                    <th>Un Approve</th>
                  </tr>
                </thead>
                <tbody id="companies_subscription_list_body">
                  <%= render "companies_list.html.erb" %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charges/new.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <%= form_tag company_charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="amount">
            <span>Amount: ₹ 1500.00</span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription"
          data-amount="1500" data-locale="auto"></script>
        <% end %>
      </div>
    </div>
  </div>
</div>